#pragma once
#include "imgui/imgui.h"
#include "imgui/imgui_impl_glfw.h"
#include "imgui/imgui_impl_opengl3.h"
#include <stdio.h>
#define GL_SILENCE_DEPRECATION
#if defined(IMGUI_IMPL_OPENGL_ES2)
#include <GLES2/gl2.h>
#endif
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <string>
#include "shader.h"
#include "camera.h"
#include <iostream>
#include <math.h>
#include <vector>
#include <map>
#include <wtypes.h>
#include <string>
#include "Object.h"
#include "Container.h"
#include "ground.h"
#include "floors.h"
#include "skybox.h"
#include "Shelf.h"
#include "wall.h"
#include "lift.h"
#include "roof.h"
#include "load_texture.h"
#include "Forklift.h"
#include "Transporter.h"
#include "Railing.h"
#include "array.h"
#include "Console.h"

